version: '3.8'

services:
    fastapi:
        build: .
        ports:
         - "8000:8000"
        depends_on:
         - postgres
        volumes:
         - ./data:/app/data
        restart: always

    postgres:
        image: postgres:15-alpine
        volumes:
         - postgres_data:/var/lib/postgresql/data
        expose:
         - 5432
        environment:
         - POSTGRES_USER=admin
         - POSTGRES_PASSWORD=8a3843e5ca1da97079290de3
         - POSTGRES_DB=sinwin
        restart: always

volumes:
    postgres_data:
